# Generated by Django 3.2.6 on 2021-08-15 04:47

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('content', froala_editor.fields.FroalaField()),
                ('image', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
